### ISSUE TITLE
Unallocated pointer freed when webp not supported

### ISSUE THREAD

**Issue by wrunk** [h2non/bimg#111]
run_web(94466,0x700000393000) malloc: *** error for object 0xc82044e000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff9bb23f06 m=8
signal arrived during cgo execution

If you load the fixtures/test.webp without vips support for webp you get a nasty crash. The flow is NewImage().Metadata() which makes its way into vipsImageType(), readImageType(buf) and in particular the defer C.free(imageBuf) seems to cause the crash (inside readImageType func).

Commenting out lines 515-517 works as I don't care to support magickbuffer for now, but perhaps there's an easy fix here. If you have a suggestion I am happy to implement, test and make a pr, otherwise Ill play with it more soon.

OSX 10.11.5
vips-8.3.3-Mon Sep 12 11:42:16 PDT 2016

**Comment by ryanfowler** [comment]
Also running into this crash.

Strangely, it is happening inconsistently with the same images. Sometimes it logs out: `vips warning: VipsJpeg: error reading resolution`, while other times it crashes.

OS: macOS 10.12
Vips: vips-8.4.1-Fri Sep 23 15:42:34 BST 2016

```
bimg.test(31275,0x70000c84c000) malloc: *** error for object 0xc4204601c0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fffbedfddda m=8
signal arrived during cgo execution

goroutine 12 [syscall, locked to thread]:
runtime.cgocall(0x42b3a70, 0xc420481718, 0x0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/cgocall.go:131 +0x110 fp=0xc4204816e8 sp=0xc4204816a8
github.com/h2non/bimg._Cfunc_free(0xc4204601c0)
	??:0 +0x41 fp=0xc420481718 sp=0xc4204816e8
github.com/h2non/bimg.readImageType.func1(0x42ea800, 0xc4204601c0)
	github.com/h2non/bimg/vips.go:525 +0x5e fp=0xc420481758 sp=0xc420481718
github.com/h2non/bimg.readImageType(0xc4204601c0, 0xa, 0x10, 0x0, 0x0)
	github.com/h2non/bimg/vips.go:526 +0xe1 fp=0xc420481798 sp=0xc420481758
github.com/h2non/bimg.vipsImageType(0xc4204601c0, 0xa, 0x10, 0xc42003f818)
	github.com/h2non/bimg/vips.go:515 +0x2d7 fp=0xc4204817d0 sp=0xc420481798
github.com/h2non/bimg.vipsRead(0xc4204601c0, 0xa, 0x10, 0x0, 0x0, 0x0, 0x0)
	github.com/h2non/bimg/vips.go:254 +0x6a fp=0xc420481848 sp=0xc4204817d0
github.com/h2non/bimg.Metadata(0xc4204601c0, 0xa, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/h2non/bimg/metadata.go:55 +0xc0 fp=0xc420481928 sp=0xc420481848
github.com/h2non/bimg.Size(0xc4204601c0, 0xa, 0x10, 0x0, 0x5a00e10, 0x0, 0x0)
	github.com/h2non/bimg/metadata.go:29 +0x5a fp=0xc420481a10 sp=0xc420481928
github.com/h2non/bimg.(*Image).Size(0xc420481d28, 0xc42003faa0, 0x4012438, 0x50, 0x4345d40)
```

**Comment by h2non** [comment]
See if this change fixes the issue:
https://github.com/h2non/bimg/commit/99cb60d305197fea26e68c5b669c05989ecd20f7

You can test it pulling from `master` from `github.com` instead of `gopkg.in`.

**Comment by ryanfowler** [comment]
Thanks for the quick reply, @h2non! I can confirm that 99cb60d fixes the issue for me.

**Comment by h2non** [comment]
`bimg@1.0.4` has been just released with the fix. Feel free to update your dependencies. Thanks for reporting.

Closing issue for now.
