### ISSUE TITLE
Upgrade to VIPS 8.4

### ISSUE THREAD

**Issue by sachinwalia2k8** [h2non/bimg#114]
VIPS 8.4 is just around the corner. Is there any plan to upgrade bimg as well imaginary to use the latest release of VIPS. BTW I really loved imaginary. Something I've been really looking for.

**Comment by h2non** [comment]
You can compile you Go program linking against the desired libvips version you want. bimg is compatible with 8.4 version.

The same goes for imaginary, unless you arr using Docker or Heroku, where in that case it would be supported soon. 

What features are you looking for that are not supported in libvips@8.3?

**Comment by h2non** [comment]
imaginary now supports libvips@8.4 via Docker image and Go 1.7.
