### ISSUE TITLE
Unsupported image format for standard jpeg file

### ISSUE THREAD

**Issue by tvmaly** [h2non/bimg#116]
I just compiled libvips 4.8.1 with debug info on OSX with libjpeg turbo support

I am getting the error "Unsupported image format"  when I try to load a standard jpeg image file.

I am using the 1.0.5 version bimg with Go version 1.7

I enabled  VIPS_TRACE=1 DEBUG=bimg  in my program and I see

vips cache+: jpegload_buffer buffer=VIPS_TYPE_BLOB, data = 0xc42014a000, length = 2427809 out=((VipsImage*) 0x587b010) flags=((VipsForeignFlags) VIPS_FOREIGN_SEQUENTIAL) access=((VipsAccess) VIPS_ACCESS_RANDOM) -

If I use same libvips in a C program and test the same image I have no problems

------------
# gcc -g -Wall try211.c `pkg-config vips --cflags --libs`
#include <stdio.h>
#include <vips/vips.h>

int
main( int argc, char **argv )
{
  GOptionContext *context;
  GOptionGroup *main_group;
  GError *error = NULL;
  VipsImage *in;
  double mean;
  VipsImage *out;

  if( VIPS_INIT( argv[0] ) )
    vips_error_exit( NULL ); 

  context = g_option_context_new( "hello infile outfile - VIPS demo" );

  main_group = g_option_group_new( NULL, NULL, NULL, NULL, NULL );
  g_option_context_set_main_group( context, main_group );
  vips_add_option_entries( main_group ); 

  if( !g_option_context_parse( context, &argc, &argv, &error ) ) {
    if( error ) {
      fprintf( stderr, "%s\n", error->message );
      g_error_free( error );
    }

    vips_error_exit( NULL );
  }

  if( argc != 3 )
    vips_error_exit( "usage: %s infile outfile", argv[0] ); 
  
  if( !(in = vips_image_new_from_file( argv[1], NULL )) )
    vips_error_exit( NULL );

  printf( "image width = %d\n", vips_image_get_width( in ) ); 

  if( vips_avg( in, &mean, NULL ) )
    vips_error_exit( NULL );

  printf( "mean pixel value = %g\n", mean ); 

  if( vips_invert( in, &out, NULL ) )
    vips_error_exit( NULL );

  g_object_unref( in ); 

  if( vips_image_write_to_file( out, argv[2], NULL ) )
    vips_error_exit( NULL );

  g_object_unref( out ); 

  return( 0 );
}
----------------

**Comment by h2non** [comment]
Can you provide the compilation flags?
Can you provide the JPEG image?

**Comment by tvmaly** [comment]
I am not sure why, but it is working today without code change.  You can close this issue, sorry to trouble you.

I compiled the go program with just  go build processimage.go

----------
package main

import (
	"fmt"
	"gopkg.in/h2non/bimg.v1"
	"os"
)

func main() {

	filename := "test3.jpg"

	buffer, err := bimg.Read(filename)

	if err != nil {
		fmt.Printf("ERROR reading image with bimg library: %s\n", err)
		os.Exit(1)
	}

	bimg.VipsDebugInfo()

	size, err := bimg.NewImage(buffer).Size()

	if err != nil {
		fmt.Printf("ERROR getting size: %s\n", err)
	} else {

		fmt.Printf("WIDTH: %d HEIGHT: %d\n", size.Width, size.Height)

	}

}

----------

For libvips I configured it with

./configure --enable-debug --with-jpeg-libraries=/opt/libjpeg-turbo/lib --with-jpeg-includes=/opt/libjpeg-turbo/include CFLAGS="-I/usr/local/include/libxml2" LDFLAGS="-L/usr/local/lib"

attached is my test image
![test3](https://cloud.githubusercontent.com/assets/726081/19149376/8bd8c1fe-8b8f-11e6-8823-bcb81fbff9a6.jpg)

**Comment by h2non** [comment]
Cool.
