### ISSUE TITLE
Combine/join one bimg.Image on top of another

### ISSUE THREAD

**Issue by tirithen** [h2non/bimg#125]
Hi, new to go as a whole so maybe I'm missing something obvious, but can I use bigm/libvips to place one PNG image on top of another (that bot have alpha transparency values) and combine them into one new image using this package?

**Comment by h2non** [comment]
Yes, but only using `libvips`. `bimg` doesn't support that yet.

**Comment by tirithen** [comment]
I'm a beginner on go so please bare with me, should I use another go package then or could I still use the C bindings that this package has to achieve this functionality?

What would in that case that approach be? The code of this package would have to be extended I guess?

**Comment by jaume-pinyol** [comment]
I've made a PR for this https://github.com/h2non/bimg/pull/132

**Comment by h2non** [comment]
Already supported. Closing.
