### ISSUE TITLE
Crop is doing resize

### ISSUE THREAD

**Issue by danpersa** [h2non/bimg#128]
I have the following program:

```go
package main

import (
	"fmt"
	"os"
	"gopkg.in/h2non/bimg.v1"
)

func main() {
	println("Hello world")

	buffer, err := bimg.Read("wide-01-4096.jpg")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
	}

	newImage, err := bimg.NewImage(buffer).CropByWidth(600)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
	}

	bimg.Write("new.jpg", newImage)
}
```

As an input, I'm using the 4k image, here: 

![wide-01-4096](https://cloud.githubusercontent.com/assets/579158/21395123/9946c15e-c79b-11e6-9733-7096ee118a59.jpg)

The problem is that the image is not cropped, but resized instead.

I also tried to use the `bimg.Options` struct and the `Process` function, with the same wrong result.

One workaround I found is to use `bimg.Options` with the height also set to the original height of the image.

**Comment by danpersa** [comment]
anybody looking at this? :)

**Comment by h2non** [comment]
hey! Gotta test that in detail, but you can workaround that explicitly defining the desired both `Width` and `Height`. Alternatively, try passing `Force: true`.

**Comment by danpersa** [comment]
I could try to find out how to fix it, next week, and do a PR if you agree :)

**Comment by h2non** [comment]
I always agree in terms of PRs ;)

**Comment by danpersa** [comment]
First a small observation about existing the crop tests.
They use a sample test image, `test.jpg` in size of 1680x1050.

The crop tests have wrong asserts:

```go
func TestImageCropByWidth(t *testing.T) {
        // ...
	err = assertSize(buf, 600, 375)
        // instead of
	err = assertSize(buf, 600, 1050)
       // ...
}

func TestImageCropByHeight(t *testing.T) {
        // ...
        err = assertSize(buf, 480, 300)
        // instead of
	err = assertSize(buf, 1680, 300)
        // ...
}
```
