### ISSUE TITLE
Doesn't work with vips 7.40.6 on debian jessie

### ISSUE THREAD

**Issue by rdixonbhw** [h2non/bimg#130]
Compiling fails with `VIPS_ANGLE45_D45`, `VIPS_ANGLE45_D135`, `VIPS_ANGLE45_D225`, and `VIPS_ANGLE45_D315` being undefined. They appear to be listed in the [8.0 documentation](http://www.vips.ecs.soton.ac.uk/supported/8.0/doc/html/libvips/libvips-conversion.html) but not the [7.40 documentation](http://www.vips.ecs.soton.ac.uk/supported/7.40/doc/html/libvips/libvips-conversion.html).

**Comment by h2non** [comment]
Please, use `libvips@7.42+` (however, it's preferably using 8.3+).

`bimg` doesn't officially support `7.40` anymore.

**Comment by rdixonbhw** [comment]
Ah, thank you for the help.
