### ISSUE TITLE
webp advanced options

### ISSUE THREAD

**Issue by nergdron** [h2non/bimg#135]
The latest libvips upstream supports advanced webp compression options, including presets, lossless, and near_lossless. It'd be great if this library supported those features as well:

https://github.com/jcupitt/libvips/pull/430
https://github.com/jcupitt/libvips/blob/master/libvips/foreign/webpsave.c

**Comment by h2non** [comment]
Cool. I will take a look. Also, PRs are always welcome.

**Comment by h2non** [comment]
Webp is already support since v1. Closing.
