### ISSUE TITLE
Strange "bad extract area" error

### ISSUE THREAD

**Issue by LeoAdamek** [h2non/bimg#136]
I'm using bimg to extract areas from images and then resize them, however I get a bad extract area from libvips when trying to perform this operation, which according to the source is thrown when the extra area extends outside the bounds of the image, which after checking the values, is not the case.

Size of the image reported by bimg: `{Width:4608 Height:3456}`
Options passed to `(*bimg.image).Process`:

````go
{Height:0 Width:0 AreaHeight:3454 AreaWidth:2592 Top:0 Left:1008 Quality:0 Compression:0 Zoom:0 Crop:false Enlarge:false Embed:false Flip:false Flop:false Force:false NoAutoRotate:false NoProfile:false Interlace:false Extend:0 Rotate:0 Background:{R:0 G:0 B:0} Gravity:0 Watermark:{Width:0 DPI:0 Margin:0 Opacity:0 NoReplicate:false Text: Font: Background:{R:0 G:0 B:0}} Type:0 Interpolator:bicubic Interpretation:0 GaussianBlur:{Sigma:0 MinAmpl:0} Sharpen:{Radius:0 X1:0 Y2:0 Y3:0 M1:0 M2:0}}
````

Code sample:

````go
if (crop.Y + scaleHeight) > size.Height {
		// Clamp crop so that bottom edge aligns with
		// original image bottom edge.
		crop.Y = size.Height - scaleHeight
	}

	// Top-left boundary checks.
	if crop.X < 0 {
		crop.X = 0
	}

	if crop.Y < 0 {
		crop.Y = 0
	}

	cropOptions := bimg.Options{
		Top:        crop.Y,
		Left:       crop.X,
		AreaWidth:  scaleWidth,
		AreaHeight: scaleHeight,
	}

	// C R O P
	croppedData, err := im.Process(cropOptions)

	if err != nil {
		logrus.WithError(err).WithFields(logrus.Fields{
			"options": cropOptions,
			"size":    size,
		}).Errorln("Unable to crop image")
		return []byte{}, err
	}
````

Any ideas why I'm getting this error when my values show I'm not asking for any area outside the image?

**Comment by LeoAdamek** [comment]
So I've realised now what is actually causing the issue.

Because the `(*bimg.Image).Size()` function (or rather the associated libvips function) is getting the dimensions from the format-specific file header, it doesn't take into account the possibility of an EXIF orientation flag. However this flag _is_ taken into account when determining if the area specified for an extract operation is valid, and where that area is.

Will look into this further but may submit a PR to add another func which gets the dimensions with the EXIF orientation applied if this resolves the issue.

**Comment by h2non** [comment]
Apologies for the delay, I'm quite busy lately. If you can provide a PR, that would be great. I will take a look asap.

**Comment by LeoAdamek** [comment]
See PR #140 which adds this enhancement.
