### ISSUE TITLE
Limit concurrent vips threads

### ISSUE THREAD

**Issue by h2non** [h2non/bimg#14]
Possible issues? It should be single-thread per image?

**Comment by h2non** [comment]
Pending tests from imaginary

**Comment by jcupitt** [comment]
You should be OK. Images are immutable and can be read by many threads. 

If you have problems, it's a bug.

**Comment by h2non** [comment]
Oh! Thank you!

**Comment by h2non** [comment]
Reopened, due to possible bug: https://github.com/jcupitt/libvips/issues/261

**Comment by h2non** [comment]
Try disabling the call to `C.vips_thread_shutdown()` in resize.go
