### ISSUE TITLE
vendor/github.com/h2non/bimg/image.go:15: undefined: Options

### ISSUE THREAD

**Issue by euskadi31** [h2non/bimg#151]
Hi, I have a problème with `go build`

go v1.8
macOS 10.12.4

```
vendor/github.com/h2non/bimg/image.go:15: undefined: Options
vendor/github.com/h2non/bimg/image.go:25: undefined: Options
vendor/github.com/h2non/bimg/image.go:82: undefined: Gravity
vendor/github.com/h2non/bimg/image.go:122: undefined: Watermark
vendor/github.com/h2non/bimg/image.go:135: undefined: Angle
vendor/github.com/h2non/bimg/image.go:159: undefined: Interpretation
vendor/github.com/h2non/bimg/image.go:167: undefined: Options
vendor/github.com/h2non/bimg/image.go:177: undefined: ImageMetadata
vendor/github.com/h2non/bimg/image.go:183: undefined: Interpretation
vendor/github.com/h2non/bimg/image.go:199: undefined: ImageSize
vendor/github.com/h2non/bimg/image.go:25: too many errors
```

**Comment by gdehmlow** [comment]
I don't see this problem on OS X 10.11.3 when building native, but I do see it when i try to cross-compile to linux.

**Comment by ajdevries** [comment]
It is important that libvips is installed:

```
vips -version
```

**Comment by euskadi31** [comment]
`vips-8.4.5-Mon Feb 13 13:08:02 CET 2017`

**Comment by euskadi31** [comment]
at home : `vips-8.6.0-Sat Apr 15 23:52:58 CEST 2017`

**Comment by uschen** [comment]
same of linux

**Comment by Dynom** [comment]
Try the build from within the Docker image, it should offer have a sane build environment:
```sh
$ docker run --rm -it -v /path/to/go/path/src/:/go/src --entrypoint=bash h2non/imaginary:latest
root@f00d:/go# cd /go/src/github.com/Dynom/imaginary
root@f00d:/go/src/github.com/Dynom/imaginary# go build -a
```

**Comment by captjt** [comment]
@euskadi31 what did you do to get this working?

**Comment by captjt** [comment]
Just want to see what the state of this issue is. I am getting the same errors on OS X 10.12.6 and Go version 1.9.1.

```
../../vendor/gopkg.in/h2non/bimg.v1/image.go:93:49: undefined: Gravity
../../vendor/gopkg.in/h2non/bimg.v1/image.go:133:29: undefined: Watermark
../../vendor/gopkg.in/h2non/bimg.v1/image.go:139:34: undefined: WatermarkImage
../../vendor/gopkg.in/h2non/bimg.v1/image.go:152:26: undefined: Angle
../../vendor/gopkg.in/h2non/bimg.v1/image.go:176:31: undefined: Interpretation
../../vendor/gopkg.in/h2non/bimg.v1/image.go:191:27: undefined: Options
../../vendor/gopkg.in/h2non/bimg.v1/image.go:201:29: undefined: ImageMetadata
../../vendor/gopkg.in/h2non/bimg.v1/image.go:207:35: undefined: Interpretation
../../vendor/gopkg.in/h2non/bimg.v1/image.go:223:25: undefined: ImageSize
../../vendor/gopkg.in/h2non/bimg.v1/resize_legacy.go:8:27: undefined: Options
../../vendor/gopkg.in/h2non/bimg.v1/resize_legacy.go:8:27: too many errors
```

- **libvips** version

```bash
vips --vips-version
libvips 8.5.9-Fri Oct 27 10:53:06 EDT 2017
```

**Comment by bpsizemore** [comment]
@captjt could you please provide more explanation?

**Comment by captjt** [comment]
Apologies @bpsizemore I was disabling cgo when I build most of my binaries. Mostly because the rest services I develop don't use any cgo bindings. This obviously will not work if I pass `CGO_ENABLED=0` while doing a go build.

**Comment by bpsizemore** [comment]
Thanks for the response @captjt I tried this but didn't solve my problem. I ended up using a container to compile. Works fine if I compile to local architecture (Sierra 10.13.2) but if I try to cross compile for linux I was getting same error.

**Comment by captjt** [comment]
If you could @bpsizemore - what environment are you trying to compile for? Also, if you are able to give me more information about your build process I am sure I can help out with this. I locally build for Sierra 10.13.2 locally as well and deployed the service built with this library in an alpine 3.7 docker container.

**Comment by bpsizemore** [comment]
My environment looks like 
go version go1.9.2 darwin/amd64
vips-8.6.1-Wed Jan  3 08:34:04 UTC 2018

Trying to compile for linux using 
```GOOS=linux go build
# gopkg.in/h2non/bimg.v1
../../go/src/gopkg.in/h2non/bimg.v1/image.go:93:49: undefined: Gravity
../../go/src/gopkg.in/h2non/bimg.v1/image.go:133:29: undefined: Watermark
../../go/src/gopkg.in/h2non/bimg.v1/image.go:139:34: undefined: WatermarkImage
../../go/src/gopkg.in/h2non/bimg.v1/image.go:152:26: undefined: Angle
../../go/src/gopkg.in/h2non/bimg.v1/image.go:176:31: undefined: Interpretation
../../go/src/gopkg.in/h2non/bimg.v1/image.go:191:27: undefined: Options
../../go/src/gopkg.in/h2non/bimg.v1/image.go:201:29: undefined: ImageMetadata
../../go/src/gopkg.in/h2non/bimg.v1/image.go:207:35: undefined: Interpretation
../../go/src/gopkg.in/h2non/bimg.v1/image.go:223:25: undefined: ImageSize
../../go/src/gopkg.in/h2non/bimg.v1/resize.go:11:27: undefined: Options
../../go/src/gopkg.in/h2non/bimg.v1/resize.go:11:27: too many errors
```

Also tried 
```
GOOS=linux CGO_ENABLED=1 go build
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

After this point I gave up and went to container for compiling, but it would be awesome to have this work properly, as I'm going to regularly need to compile for linux. Let me know if there is any other information you need. 

I did read that it was probably because I was using a different C compiler, but I don't have a clue how to go about changing the default on a Mac.

**Comment by captjt** [comment]
I don't know how you would be able to cross compile to a linux architecture with Mac OSX C libraries. It's out of my range of knowledge there. I would definitely recommend containerize the application and if you don't have that luxury at least run your build process for the linux environment in a container that mirrors where you want to deploy.

**Comment by h2non** [comment]
Obsolete issue. Closing.

**Comment by yangxin520520** [comment]
#  GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o main .
# github.com/h2non/bimg
vendor/github.com/h2non/bimg/image.go:93:49: undefined: Gravity
vendor/github.com/h2non/bimg/image.go:133:29: undefined: Watermark
vendor/github.com/h2non/bimg/image.go:139:34: undefined: WatermarkImage
vendor/github.com/h2non/bimg/image.go:152:26: undefined: Angle
vendor/github.com/h2non/bimg/image.go:181:31: undefined: Interpretation
vendor/github.com/h2non/bimg/image.go:202:27: undefined: Options
vendor/github.com/h2non/bimg/image.go:212:29: undefined: ImageMetadata
vendor/github.com/h2non/bimg/image.go:218:35: undefined: Interpretation
vendor/github.com/h2non/bimg/image.go:234:25: undefined: ImageSize
vendor/github.com/h2non/bimg/resize.go:11:27: undefined: Options
vendor/github.com/h2non/bimg/resize.go:11:27: too many errors

**Comment by AlTheOne** [comment]
Who is resolved this problem ?

**Comment by vithubati** [comment]
I fixed it by removing CGO_ENABLED=0 from the build command as Bimg depends on GCC. 
And also if you are building inside Dockerfile, make sure to install libvips-dev
`RUN apt update && apt install -y libvips-dev`

**Comment by evandrosouza89** [comment]
I'm having the same issue

**Comment by PerrywLiu** [comment]
I'm having the same issue in docker

**Comment by 4kpros** [comment]
If you want to use Docker, here's a Dockerfile example using Alpine with Go 1.23.2 (the latest version at the time of writing).

```
FROM golang:alpine AS builder
ENV LANG=C.UTF-8

WORKDIR /app

# Install packages
RUN apk update &&\
    apk add --update --no-cache bash curl \
    gcc g++ vips vips-dev vips-poppler pkgconf \
    poppler-dev musl-dev libc6-compat

# Copy the project files
COPY . .

# Install dependencies and build the app
RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o ./.build/main ./main.go

# Now your app binary is available at ./.build/main

**Comment by PascalTemel** [comment]
I was trying to build on a fresh cloud server instance and had similar issues. For me the solution was installing build-essential and pkg-config.
