### ISSUE TITLE
Support for image concatenation

### ISSUE THREAD

**Issue by ernsheong** [h2non/bimg#173]
Hi all, does bimg support image concatenation?

I'm trying to concatenate multiple images vertically/horizontally into one piece.

**Comment by greut** [comment]
afaik, bimg doesn't support it. But `libvips` does.

- [vips_insert](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-insert)
- [vips_join](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-join)
- [vips mosaicing](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-mosaicing.html)

What is your use case?

**Comment by ernsheong** [comment]
Thanks. I was trying to capture full page HTML page screenshots via Chrome extension (which only supports visible tab capture) and send them to server for stitching into one piece. Canvas could do it at the cost of more FE processing. But I realize full page screenshots will be flawed when done this way due to position fixed elements. Just gonna wait till Chrome opens up that feature to extensions, or else find a way to get Chrome to do it (since Chrome 59 it is supported) for me.

**Comment by greut** [comment]
Gecko (through slimerjs) supports fullpage screenshot: https://docs.slimerjs.org/current/api/webpage.html#render-filename-options

Firefox 56 will get headless mode, like Chrome, hopefully.

**Comment by greut** [comment]
```
$ vips join a.png b.png out.png vertical
$ convert -append a.png b.png c.png out.png
```
