### ISSUE TITLE
How is it crop circle?

### ISSUE THREAD

**Issue by zanjs** [h2non/bimg#176]
Is it possible to take a square or rectangle image and crop it to a circle with this library?

@Dynom 

Use ImageMagick look this.

https://stackoverflow.com/questions/999251/crop-or-mask-an-image-into-a-circle

**Comment by h2non** [comment]
Not currently.

**Comment by zanjs** [comment]
Here is one way with ImageMagick that will acomplish this without using a mask:

```sh
convert -size 200x200 xc:none -fill walter.jpg -draw "circle 100,100 100,1" circle_thumb.png
```

![](https://i.stack.imgur.com/Yu5xU.jpg) ![](https://i.stack.imgur.com/pO6zJ.png)

**Comment by Dynom** [comment]
It's still a mask, with a transparent "color". In any case that's not cropping, or at least it's not the terminology I would use.

Either way the answer is: That is currently unsupported.
