### ISSUE TITLE
vips_watermark failed when input image has 4 bands

### ISSUE THREAD

**Issue by sanlee42** [h2non/bimg#177]
If input image is png(which has the alpha channel), watermark will be failed.
The error msg is `ifthenelse: not one band or 4 bands`.
Does it means watermark only support for the input image with 3 bands?

**Comment by greut** [comment]
To fix it, one have to make the compositing manually.

- https://github.com/jcupitt/libvips/issues/657

**Comment by egor-manjula** [comment]
Hi! Is there any news on that? I am really waiting for the fix.

**Comment by greut** [comment]
@egor-manjula what do you mean by _waiting for the fix_?

My best guess is that you either have to make it yourself by doing the composition manually, or finding someone able to do so and negociate how many 🍻 or 🍭 they would ask for their trouble.

**Comment by egor-manjula** [comment]
@greut I am really newbie into go lang, just start learning it. I've tried ti find out on what is wrong in the code but failed with that. Coukd you please send me some example on nanual composition or at list send a link, or point ot lines number if they are already exists somewhere.

**Comment by greut** [comment]
The option one seems out of reach then.

**Comment by timotew** [comment]
@yehor-manzhula were you able to sole this issue?

**Comment by yehor-manzhula** [comment]
@timotew Nope.

**Comment by timotew** [comment]
I converted the image to JPEG fist before adding watermark was the bypass I used.

**Comment by akbarsigit** [comment]
> I converted the image to JPEG fist before adding watermark was the bypass I used.

@timotew it works! thanks 😄
