### ISSUE TITLE
Allow setting of save "strip" parameter via Options?

### ISSUE THREAD

**Issue by oadk** [h2non/bimg#189]
Hi, first, thanks for the great work on bimg. 

My question: I noticed images have their EXIF data stripped when calling `bimg.Resize()`. This behaviour is explained by the fact that the `vipsSave()` function in `vips.go` always passes 1 for the `strip` parameter to the various `vips_*save_bridge()` functions.

Would it be possible to allow this parameter to be set via the `vipSaveOptions` and `Options` structs, please? This would allow us to optionally propagate EXIF data when the image is saved.

Thanks for your help.

**Comment by h2non** [comment]
This was introduced in `bimg@1.0.11`. Try it upgrading the package:
```bash
go get -u gopkg.in/h2non/bimg.v1
```

**Comment by h2non** [comment]
See new option field `StripMetadata bool` in `bimg.Options` struct:
https://godoc.org/github.com/h2non/bimg#Options

**Comment by oadk** [comment]
Hi, thanks for the quick response and release! Much appreciated.
