### ISSUE TITLE
Installation problem,

### ISSUE THREAD

**Issue by mytc** [h2non/bimg#199]
I tried to install the package by follow the installation instructions. But somehow I can't make it.

This is where I got:

> Package vips was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vips.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vips' found
> 
The bash script give me this:

> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> bash: line 15: cd: vips-8.4.2: No such file or directory
> bash: line 16: ./configure: No such file or directory
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.
> rm: cannot remove 'vips-8.4.2.tar.gz': No such file or directory
> /sbin/ldconfig.real: /usr/lib/nvidia-375/libEGL.so.1 is not a symbolic link
> 
> /sbin/ldconfig.real: /usr/lib32/nvidia-375/libEGL.so.1 is not a symbolic link
> 
Seem the script problem, any idea why?

I am using Ubuntu 16.04.3 

Thanks

**Comment by mytc** [comment]
I found the problem. 

The download link in the bash script (https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh) is not valid anymore. They have moved to github for the package downloads. 

So, I just copy the bash script and save it locally on my computer, then change the download url in the script as well as the latest version libvips.  Just change the few lines at the beginning of the script until the curl command. 
```
#!/bin/bash

vips_version_minimum=8.4.2
vips_version_latest_major_minor=8.5
vips_version_latest_patch=9

openslide_version_minimum=3.4.0
openslide_version_latest_major_minor=3.4
openslide_version_latest_patch=1

install_libvips_from_source() {
  echo "Compiling libvips-$vips_version_latest_major_minor.$vips_version_latest_patch from source"
 
  curl -LOk https://github.com/jcupitt/libvips/releases/download/v$vips_version_latest_major_minor.$vips_version_latest_patch/vips-$vips_version_latest_major_minor.$vips_version_latest_patch.tar.gz
.....
```

**Comment by h2non** [comment]
Thanks for reporting this. Can't fix it now (travelling) but if anyone is interested, feel free to open a PR.

**Comment by h2non** [comment]
This should be fixed in `master`. For details, see:
https://github.com/h2non/bimg/commit/ba1cf6a030d8fd1091ffd24df8d13bbc555448d5
