### ISSUE TITLE
Crop image with an indent

### ISSUE THREAD

**Issue by Divitay** [h2non/bimg#200]
How do I perform a crop with an indent from the left and from above for example?
For example, I need to crop an image, with parameters
`left:0, top:0, width:200, height:200`
How can i do this?
Help me please :(

**Comment by h2non** [comment]
Not sure if I got what you need, buy why not extract area first and then perform the crop in order to fit a concrete resolution?

**Comment by Divitay** [comment]
Could you give an example please?
``` 
imgResize, _ := bimg.NewImage(data).Crop( ?? )
bimg.Write(path, fileToSave) 
```

**Comment by h2non** [comment]
What about something like this?
```go
img := bimg.NewImage(data)
_, err := img.Extract(top, left, width, height)
if err != nil {
  return err
}
_, err := img.Crop(width, height, gravity)
if err != nil {
  return err
}
bimg.Write(path, img.Image()) 
```
```
