### ISSUE TITLE
go-debug has been removed

### ISSUE THREAD

**Issue by mircea-cosbuc** [h2non/bimg#215]
The dependency https://github.com/h2non/bimg/blob/master/Gopkg.toml#L25 has been removed from github and running `dep ensure` on a project using `bimg` fails at the moment.

**Comment by h2non** [comment]
Oops! I don't know where it went. Hopefully @tj can help us here.

**Comment by tj** [comment]
ah yea sorry, I think that pkg is an anti-pattern so I removed it, feel free to re-push it as your own pkg if you want

**Comment by h2non** [comment]
Thanks for the quick answer. I guess porting packages from node to Go can be often considered an anti-pattern haha

**Comment by tj** [comment]
I just use a logger with debug level now :D feels less hacky
