### ISSUE TITLE
embed is cropping image

### ISSUE THREAD

**Issue by kishorgandham** [h2non/bimg#223]
I am trying to resize an image with width:500 and height:500 to width:250 and height:100 with embed option. My intent is to retain the aspect ratio of the original image during resize operation and pad whitespace to match the new dimensions. In this example, it would mean, the original image would be resized to 100x100 and then embedded in a white background image of size 250x100

Following is the code I used to achieve this with bimg:
```
options := bimg.Options{
				Width:      250,
				Height:     100,
				Embed:      true,
				Extend:     4,
				Crop:       false,
				Force:      false,
				Background: bimg.Color{255, 255, 255},
			}

			bimg.NewImage(buf).Process(options)
```

However, the above code is creating an image of size 250x100 by cropping the original image and not embedding in a white background

Am I doing something wrong here, or is there a bug in bimg?

I am using libvips 8.6.1 and the latest version of bimg

**Comment by kishorgandham** [comment]
After further debugging, this looks like a regression issue introduced in [https://github.com/h2non/bimg/commit/e7d6d147eeb9e53dd4351c5e2da52ddd0981564d#diff-e2d75d285d6ec44674c6ac3035cd47f7](https://github.com/h2non/bimg/commit/e7d6d147eeb9e53dd4351c5e2da52ddd0981564d#diff-e2d75d285d6ec44674c6ac3035cd47f7)

[https://github.com/h2non/bimg/blob/02e621739c77c791d8c153f240b7a1f75b07816f/resizer.go#L449](https://github.com/h2non/bimg/blob/02e621739c77c791d8c153f240b7a1f75b07816f/resizer.go#L449)
Changing the above code to:
`if o.Crop {
    factor = math.Min(xfactor, yfactor)
} else {
    factor = math.Max(xfactor, yfactor)
}`
seems to resolve the issue

**Comment by skidder** [comment]
I was able to confirm that this fix is working as intended.
