### ISSUE TITLE
Unable to build bimg in Go 1.11 (Linux)

### ISSUE THREAD

**Issue by tssajo** [h2non/bimg#252]
I decided to open a new ticket for this issue because an old one I've found for Go 1.9.x (https://github.com/h2non/bimg/issues/230) was never closed and the error message I get this time is slightly different. Maybe someone will look into it this way!

I try to build a Go program we wrote on Debian Linux (Jessie), it is importing the `bimg` library like this:

```
import (
        bimg "gopkg.in/h2non/bimg.v1"
)
```

Here is what I get when I try to build it with Go 1.11:

```
# go build
go build gopkg.in/h2non/bimg.v1: invalid flag in pkg-config --libs: -Wl,--export-dynamic
```

This works with Go 1.9.6 ! But I cannot build it with Go 1.10.x nor with Go 1.11

Here are some more info about the system I am trying to make it build on:

```
# lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie
```
```
# go version
go version go1.11 linux/amd64
```
```
# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tss/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414295438=/tmp/go-build -gno-record-gcc-switches"
```

Any help with this would be appreciated!

EDIT:
Also created a ticket for this on golang / go : https://github.com/golang/go/issues/27496

**Comment by h2non** [comment]
Deprecated. Please use `libvips@8.9+` with `bimg@1.1+`.

**Comment by shrimalmadhur** [comment]
@h2non I am getting a similar issue but with a different flag
```
go build github.com/h2non/bimg: invalid flag in pkg-config --cflags: -Xpreprocessor
```

bimg version - `github.com/h2non/bimg v1.1.5`
libvips version - `8.11.2`
go version - `1.15.6`
`macOS 11.4`

Any idea how can I fix this?
