### ISSUE TITLE
Create new release?

### ISSUE THREAD

**Issue by bbernhard** [h2non/bimg#269]
Currently, the install instructions as described in the README, don't seem to work. I think that's mostly due to this commit here: https://github.com/h2non/bimg/commit/5304c52ca67af7af5ebce8c18fe8b6c8add2e4e5#diff-7e6ff60b79f74e556b8aed6bbd3c3593. 

The commit updates the vips version and fixes the `vips_rotate` name clash. But unfortunately, bimg.v1 still points to the v1.0.18 release (see https://gopkg.in/h2non/bimg.v1). So when using the `preinstall.sh` script and then doing a `go get -u gopkg.in/h2non/bimg.v1` one ends up with the following error: 

```
./vips.h:180:1: error: conflicting types for 'vips_rotate'
 vips_rotate(VipsImage *in, VipsImage **out, int angle) {
 ^~~~~~~~~~~
In file included from /usr/local/include/vips/vips.h:145:0,
                 from ./vips.h:3,
                 from /home/imagemonkey/go/src/gopkg.in/h2non/bimg.v1/vips.go:5:
/usr/local/include/vips/resample.h:85:5: note: previous declaration of 'vips_rotate' was here
 int vips_rotate( VipsImage *in, VipsImage **out, double angle, ... )
```

**Comment by danpersa** [comment]
Please create a new release. The current one is not compatible with vips 8.7.x.

**Comment by devmarco** [comment]
Any ETA on that?

**Comment by h2non** [comment]
It was pushed 2 days ago:
https://github.com/h2non/bimg/releases/tag/v1.0.19

**Comment by Dynom** [comment]
Ah apologies, I forgot to add a reply to this ticket!

**Comment by h2non** [comment]
Thanks @Dynom 👍
