### ISSUE TITLE
Auto rotate and flip not working correctly

### ISSUE THREAD

**Issue by momo13** [h2non/bimg#279]
Testing bimg.Resize (as of v1.0.19) with all examples from  https://github.com/recurser/exif-orientation-examples shows that autorotation and flipping is not done correctly for jpegs with exif orientation 2,4,5 and 7.

With the following changes results are correct:

1. Change order of rotate and flip such that flip is done before rotate.

```
func rotateAndFlipImage(image *C.VipsImage, o Options) (*C.VipsImage, bool, error) {
	var err error
	var rotated bool

	if o.NoAutoRotate == false {
		rotation, flip := calculateRotationAndFlip(image, o.Rotate)
		if flip {
			o.Flip = flip
		}
		if rotation > 0 && o.Rotate == 0 {
			o.Rotate = rotation
		}
	}

	if o.Flip {
		rotated = true
		image, err = vipsFlip(image, Vertical)
	}

	if o.Flop {
		rotated = true
		image, err = vipsFlip(image, Horizontal)
	}

	if o.Rotate > 0 {
		rotated = true
		image, err = vipsRotate(image, getAngle(o.Rotate))
	}

	return image, rotated, err
}
```

2. Change results for exif orientation 2 and 4:

```
func calculateRotationAndFlip(image *C.VipsImage, angle Angle) (Angle, bool) {
	rotate := D0
	flip := false

	if angle > 0 {
		return rotate, flip
	}

	switch vipsExifOrientation(image) {
	case 6:
		rotate = D90
		break
	case 3:
		rotate = D180
		break
	case 8:
		rotate = D270
		break
	case 2:
		flip = true
		rotate = D180
		break // flip 1
	case 7:
		flip = true
		rotate = D270
		break // flip 6
	case 4:
		flip = true
		break // flip 3
	case 5:
		flip = true
		rotate = D90
		break // flip 8
	}

	return rotate, flip
}

```
I haven't tested it for other cases than a simple resize. Thus not knowing whether the changes would affect other calls leading to incorrect results.

**Comment by momo13** [comment]
Also when running your tests and opening output files from TestRotationAndFlip you can see that these are not rotated and flipped correctly.

**Comment by vposhamod** [comment]
Just changing the values for 2,4,5,7 in resizer.go as following worked fine for me.

2 : rotate=180 and filp=true
4: rotate=180 and flop=true
5: rotate=90 and flop=true
7: rotate=90 and flip=true

I have tested in h2non/imaginary and it worked out well for me.

**Comment by momo13** [comment]
Hi again, I again had a look at it, as I needed to fix it locally.
I think the problem is only within the method rotateAndFlipImage. When calling vipsFlip the option Horizontal and Vertical are interchanged. It has to be:

if o.Flip {
	rotated = true
	image, err = vipsFlip(image, Horizontal)
}

if o.Flop {
	rotated = true
	image, err = vipsFlip(image, Vertical)
}

Changing it leads to correct results for the test TestRotationAndFlip. Looking at https://libvips.github.io/libvips/API/current/libvips-conversion.html#VipsDirection this makes sense.
