### ISSUE TITLE
Issues building vips library from go

### ISSUE THREAD

**Issue by hawaiiansurfer** [h2non/bimg#280]
I am trying to run/build a GoLang package that uses vips. When I try to compile the program I get this error:
``` go build gopkg.in/h2non/bimg.v1: invalid flag in pkg-config --cflags: -Xpreprocessor```

Here are my specs:
```
macOS Mojave Version 10.14.3
vips Version 8.7.4
go Version 1.11.5 darwin/amd64
```
I read some issues adding CGOALLOWEDFLAGS I've tried that also but no luck.

**Comment by pohang** [comment]
https://github.com/golang/go/wiki/InvalidFlag

Did you try `CGO_ALLOWED_FLAGS` (with the underscores)?
Something like `export CGO_CFLAGS_ALLOW="-Xpreprocessor"`.

**Comment by hawaiiansurfer** [comment]
Yes, I tried it and it worked for me, thanks!
