### ISSUE TITLE
Could not install libvips by running the script on macOS Catalina

### ISSUE THREAD

**Issue by codingrhythm** [h2non/bimg#304]
When I try to install the `libvips` by running the `preinstall.sh`, I get the following error

```
Could not find libvips using a PKG_CONFIG_PATH of ':/usr/local/lib/pkgconfig:/usr/lib/pkgconfig'
Sorry, I don't yet know how to install libvips on Darwin XXXXXXX-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct  9 13:26:26 PDT 2019; root:xnu-6153.40.150.111.1~2/RELEASE_X86_64 x86_64
```

**Comment by martip07** [comment]
This may help you: https://github.com/h2non/bimg/issues/295

**Comment by h2non** [comment]
`preinstall.sh` is deprecated and will be eventually deleted.
Please, follow `libvips` instructions: https://libvips.github.io/libvips/install.html
