### ISSUE TITLE
Very high memory usage on png resize (8GB heap alloc for 30 images)

### ISSUE THREAD

**Issue by dewey** [h2non/bimg#321]
Hey,

I'm debugging this issue for a few days already now and I just can't find a solution, maybe someone here has an idea what else I can try.

I'm using:

- Go 1.13
- `vips` latest from [alpine](https://pkgs.alpinelinux.org/package/edge/community/x86/vips): 8.9.1-r0
- bimg via Go modules: `github.com/h2non/bimg v1.0.19`

I'm resizing a bunch of `png` files that are each around 3000px (width and height). I'm trying it with 5, 10, 30 of them at the same time (A html file with 5,10,30 image tags in it linking to the scaler). For 30 images the memory usage goes up to 8GB as you can see here in this Prometheus screenshot.

<img width="1314" alt="Screenshot 2020-03-11 at 22 21 17" src="https://user-images.githubusercontent.com/790262/76469659-01fe5480-63ef-11ea-9d17-4304e6a08455.png">

I set various options that I found in other issues here:

- `MALLOC_ARENA_MAX=2` according to https://github.com/h2non/bimg/issues/282#issuecomment-556014222
- `bimg.VipsCacheSetMaxMem(0)` and `bimg.VipsCacheSetMax(0)` according to https://github.com/h2non/bimg/issues/282#issuecomment-497383052

My Dockerfile where I install vips looks like this:

```
FROM golang:1.13-alpine as builder

RUN apk add git bash pkgconfig vips-dev vips gcc musl-dev

ENV GO111MODULE=on

# Add our code
COPY ./ /src

# build
WORKDIR /src
RUN go get -u github.com/solher/forklift && \
    cd /src && \
    forklift -extensions sql > ./cmd/api/forklift.go && \
    GOGC=off CGO_CFLAGS_ALLOW=-Xpreprocessor go build -mod=vendor -v -o /scaler ./cmd/api/

# multistage
FROM alpine:latest

RUN apk --update upgrade && \
    apk add curl ca-certificates && \
    apk add vips-dev vips && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

COPY --from=builder /scaler /usr/bin/scaler

# Run the image as a non-root user
RUN adduser -D lc
RUN chmod 0755 /usr/bin/scaler

USER lc

ENV MALLOC_ARENA_MAX=2

CMD scaler
```

Sample code of how I use bimg:

```
package scaling

import (
    "github.com/h2non/bimg"
)

type bimgService struct{}

func init() {
    bimg.VipsCacheSetMaxMem(0)
    bimg.VipsCacheSetMax(0)
}

// NewBimgService returns a newly initialized scaling service
func NewBimgService() (*bimgService, error) {
    return &bimgService{}, nil
}

func (r *bimgService) Resize(b []byte, width int, height int) ([]byte, string, error) {
    newImage := bimg.NewImage(b)
    ni, err := newImage.Resize(width, height)
    if err != nil {
        return nil, "", err
    }
    return ni, getImageMimeType(bimg.DetermineImageType(ni)), nil
}
```

Also the memory usage *after* the resizing never goes down:

<img width="968" alt="Screenshot 2020-03-11 at 22 31 53" src="https://user-images.githubusercontent.com/790262/76469982-cc0da000-63ef-11ea-9bc1-6d59cfbd5c0a.png">

Is this expected? Is there a better way to get more debug information?

Thanks in advance, happy to provide more information if needed!

**Comment by dewey** [comment]
After a few more hours of debugging and pprof'ing I figured out it's unrelated to bimg / vips. It was related to minio (https://github.com/minio/minio-go/issues/1081#issuecomment-467760535) which allocates a lot of memory if no file size is provided when streaming to S3.

Sorry for the false alarm.

**Comment by harshavardhana** [comment]
The problem is the application itself, application if insists on passing `-1` size then an appropriate PartSize should be set. If the size is known it should the size appropriately.

https://github.com/minio/minio-go/issues/1176#issuecomment-546856662
