### ISSUE TITLE
`master` fails to build when libvips < version 8.8

### ISSUE THREAD

**Issue by szatmary** [h2non/bimg#322]
Commit https://github.com/h2non/bimg/commit/a875ddcd6cf1542fba1edbfd28f50664ce5943d6 added support for HEIF for when libvips >= v8.8

Several `#if` selectively compile in support for `HEIF` `C.HEIF`, defined in `vips.h` is referenced inside `vips.go`. However `C.HEIF` is compiled out of the `types` enum when libvips < v8.8

Removing this one check should allow the go to to compile:
https://github.com/h2non/bimg/commit/a875ddcd6cf1542fba1edbfd28f50664ce5943d6#diff-d5b738d5a89e99da4b60037a0b63177bR36

And `VipsIsTypeSupported(HEIF)` will still return 0.

**Comment by h2non** [comment]
Fixed in `master`. See CI builds: https://travis-ci.org/github/h2non/bimg/builds/695997864
