### ISSUE TITLE
imageFlatten should support non-PNG images

### ISSUE THREAD

**Issue by bradencanderson** [h2non/bimg#335]
It looks like libvips supports more formats than just PNG:

```
vips flatten test.heic foo.jpeg --background 65535
```

https://github.com/h2non/bimg/blob/e62b970bd78b89df47cdfb2c65e2a39663cd02f3/resizer.go#L386

Is there any history on why this method only supports PNG? According to git it's 3 years old. Maybe time to revisit it? If the solution is a simple matter of removing the gate then I'm happy to submit a PR.

**Comment by h2non** [comment]
This should definitively be updated. It would be great if you could send a PR!

**Comment by h2non** [comment]
Solved in `v1.1.0`. Closing.

**Comment by kahoona77** [comment]
Hi,
I was wondering why the flatten function is restricted to PNG, HEIF, or WEBP? 
I was testing it with TIFF-Images and that also worked fine. Maybe the restriction to image-formats can be removed completely?

**Comment by h2non** [comment]
@kahoona77 Yes, the thing is now available on `v1.1.2`.
