### ISSUE TITLE
Checksum Mismatch

### ISSUE THREAD

**Issue by Bluskript** [h2non/bimg#336]
This has occurred on both my home computer and Github CI during installation:
```
gopkg.in/h2non/bimg.v1@v1.1.0: verifying module: checksum mismatch
        downloaded: h1:a7FEB3jtuWf0Jyl7P5XJ7azpD0bQs6eIPRBcVFTqeZ0=
        sum.golang.org: h1:z/w1wCsupKtXg/TMQ3mLSh4QnZPtioH5lLejh3ZiFns=
```

**Comment by h2non** [comment]
Can you try the new import path `github.com/h2non/bimg` and run `go mod download` from scratch?

**Comment by Bluskript** [comment]
![image](https://user-images.githubusercontent.com/52386117/84049918-064cf600-a97b-11ea-8d80-427b58061fff.png)
does not work with new import path. I am installing it outside of a module to prevent weird versioning issues.

**Comment by h2non** [comment]
Could you try upgrading the package: `go get -u github.com/h2non/bimg`?

**Comment by Bluskript** [comment]
![image](https://user-images.githubusercontent.com/52386117/84080410-2516b100-a9aa-11ea-8fcf-69a0b6c15ef1.png)
same error

**Comment by h2non** [comment]
Please, update `go.mod`/`go.sum` file to use `v1.1.1`.

**Comment by Bluskript** [comment]
It works now! Thanks for the fix, no more hash mismatches.
