### ISSUE TITLE
Not working in windows

### ISSUE THREAD

**Issue by rajkumarks7** [h2non/bimg#350]
go get gopkg.in/h2non/bimg.v1
pkg-config --cflags vips vips vips vips
pkg-config: exec: "pkg-config": executable file not found in %PATH%

**Comment by h2non** [comment]
Please use the updated import path: 
`go get -u github.com/h2non/bimg`

**Comment by yuzhen1024** [comment]
![20220325](https://user-images.githubusercontent.com/47154428/160049707-b0a38f10-3fd2-4f73-81be-2c3a1e229eac.png)
