### ISSUE TITLE
Unable to build  github.com/h2non/bimg: invalid flag

### ISSUE THREAD

**Issue by sahilpaudel-pe** [h2non/bimg#352]
Go: **go version go1.13.5 darwin/amd64**
bimg: **Version = "1.1.4"**

Error: 
`go build github.com/h2non/bimg: invalid flag in pkg-config --cflags: -Xpreprocessor`

Expectaion: build successful

**Comment by h2non** [comment]
Duplicated. See: https://github.com/h2non/bimg/issues/330#issuecomment-629051552
