### ISSUE TITLE
The compression option does not take effect

### ISSUE THREAD

**Issue by guowei-gong** [h2non/bimg#386]
go version go1.16.6 darwin/amd64
I installed other dependencies through brew install.

I use a picture in jpg format as the input source, everything works fine.Through the quality option, the image size has become smaller.

code:
![image](https://user-images.githubusercontent.com/62499904/139643977-fc960d06-0d29-45e8-a5a7-9cbc836916f6.png)

result:
![image](https://user-images.githubusercontent.com/62499904/139644034-5e37d42c-2073-414d-9252-66780f54e54e.png)

When I try to compress pictures in png format, its compression effect is very poor.

code:
![image](https://user-images.githubusercontent.com/62499904/139644541-f0171936-8120-4879-b4d9-f75ca70577b0.png)

result:
![image](https://user-images.githubusercontent.com/62499904/139644639-08854659-6687-4a90-9d43-588e1b53e885.png)

If I change the Compression option to 1, its image size becomes larger?

code: 
![image](https://user-images.githubusercontent.com/62499904/139644825-adfb14fd-5922-4097-84d3-4da1a7ca264b.png)

result:
![image](https://user-images.githubusercontent.com/62499904/139644854-acf00f08-2da7-48c1-92be-8a1ea56ad2a8.png)

Thank you in advance for your help.
My English is not very good.

**Comment by rockmantist** [comment]
Hey did you found the fix on this ? i have the same issue as you, my image became larger when i put the compression

**Comment by Aldiwildan77** [comment]
This issue closed without a solution? @guowei-gong Can u provide your solution ?

**Comment by guowei-gong** [comment]
> This issue closed without a solution @guowei-gong? Can u provide your solution?

I changed the suffix of the picture of `.png` to the suffix of `.jpg`, which is effective

**Comment by guowei-gong** [comment]
> I changed the suffix of the picture of `.png` to the suffix of `.jpg`, which is effective

I changed the suffix of the picture of .png to the suffix of .jpg, which is effective
