### ISSUE TITLE
Enable more options in `vips_pngsave_bridge`

### ISSUE THREAD

**Issue by vaibsharma** [h2non/bimg#397]
Hey @h2non,

Is it possible to enable more params in `vips_pngsave_bridge` https://github.com/h2non/bimg/blob/master/vips.h#L333.
For eg - few params like `quality` and `effort` are some good options to add. https://github.com/libvips/libvips/blob/v8.12.2/libvips/foreign/pngsave.c#L535. 

Would love to get your opinion on this.

Thanks and Regards,
Vaibhav

**Comment by vaibsharma** [comment]
Just for reference.. this issue is resolved in https://github.com/h2non/bimg/pull/398/files

**Comment by h2non** [comment]
A new bimg version is available: `v1.1.7`
