### ISSUE TITLE
build failed: undefined reference to vips_reduce'

### ISSUE THREAD

**Issue by zhangtiedong0912** [h2non/bimg#399]
**golang 1.16.1**
**ubuntu:16.04**

#dockerfile
`
RUN apt-get update \
    && apt-get install -y \
    libvips libvips-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*`

In function `vips_reduce_bridge':
/root/go/pkg/mod/github.com/h2non/bimg@v1.1.7/vips.h:133: undefined reference to `vips_reduce'
collect2: error: ld returned 1 exit status
# github.com/h2non/bimg
In file included from /root/go/pkg/mod/github.com/h2non/bimg@v1.1.7/vips.go:5:0:
/root/go/pkg/mod/github.com/h2non/bimg@v1.1.7/vips.h: In function 'vips_reduce_bridge':
/root/go/pkg/mod/github.com/h2non/bimg@v1.1.7/vips.h:133:9: warning: implicit declaration of function 'vips_reduce' [-Wimplicit-function-declaration]
  return vips_reduce(in, out, xshrink, yshrink, NULL)

**Comment by zhangtiedong0912** [comment]
hi @h2non  could you please help?

**Comment by h2non** [comment]
Just check you are compiling against a compatible libvips version (v8+)

**Comment by zhangtiedong0912** [comment]
Thanks , i use v8.2.x and i change it to v8.9.x. this issue is fixed
