### ISSUE TITLE
Openslide dependency

### ISSUE THREAD

**Issue by bfitzsimmons** [h2non/bimg#40]
When installing VIPS using the provided gist, a dependency on openslide is introduced, and therefore a requirement to run Homebrew as root is also introduced.  This is officially "not supported" by Homebrew, and kills the script if you have installed Homebrew as required.

The failure:
```bash
$ curl -s https://bitbucket.org/api/2.0/snippets/bfitzsimmons/AaAk/52663c0a731eebeac46bd60bb2d9b1e7916417c2/files/vips_install | sudo bash -
Could not find libvips using a PKG_CONFIG_PATH of '/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig'
Detected Mac OS
Installing libvips via homebrew
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

The reason for the failure (note the password prompt):
```bash
$ brew install Caskroom/cask/xquartz
==> Tapping Caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
...
==> Checking out tag v0.54.0
🍺  /usr/local/Cellar/brew-cask/0.54.0: 2634 files, 10M, built in 4 seconds
==> brew cask install Caskroom/cask/xquartz
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
...
🍺  xquartz staged at '/opt/homebrew-cask/Caskroom/xquartz/2.7.7' (64M)
```

I know that the gist is coming from the sharp project, but if bimg does not require openslide, should a new gist be created that avoids the dependency?  Perhaps a modification of the current one?

**Comment by h2non** [comment]
With the latest install script from sharp, OpenSlide dependency is completely [optional](https://github.com/lovell/sharp/blob/master/preinstall.sh#L81).

I've just added the [install instructions](https://github.com/h2non/bimg/commit/cc627a48a68fc2050dad16679478bdf976f9c0cc) to install libvips with OpenSlide.

This should probably fix the permissions issue in OSX

**Comment by bfitzsimmons** [comment]
> I've just added the install instructions to install libvips with OpenSlide.

Did you mean to say "without OpenSlide"?

**Comment by bfitzsimmons** [comment]
I guess I should just look at the instructions.  :)

**Comment by bfitzsimmons** [comment]
Okay.  Got it.

**Comment by h2non** [comment]
There isn't any implicit dependency by default with OpenSlide.

That said, the bash install script (which is the same as sharp project uses) now provides a way to install OpenSlide just passing an additional flag. So, I believe that's all, indeed.

I'd recommend you to use the provided script and follow the instructions, and if you have specific troubles with the installation or you have additional requirements/dependencies, feel free to report it in the sharp repository or simply improve the install script.

**Comment by bfitzsimmons** [comment]
I'm currently just running the following to do the install on OS X:

```bash
brew install homebrew/science/vips --without-fftw --without-libgsf --without-pango --without-pygobject3   --without-gobject-introspection --without-python
```

I'll try the install script again at some point in the future.

Thanks for looking into this.

**Comment by h2non** [comment]
No worries. Thank you for the interest in the project.

I'll close this for now.

**Comment by bfitzsimmons** [comment]
Just a point of clarification, further research revealed that the reason this was causing me a problem is the following block:

```bash
# Verify root/sudo access
if [ "$(id -u)" -ne "0" ]; then
  echo "Sorry, I need root/sudo access to continue"
  exit 1
fi
```

This requires that the user be running this as `root` or it won't run regardless of whether you're attempting to install OpenSlide or not.  That appears to be the real problem.

**Comment by h2non** [comment]
Oh, I see. So let's more the discussion to the sharp project scope. I'm sure that @lovell could provide you well justified reasons about why the script requires root permissions in all cases and platforms.

**Comment by lovell** [comment]
Hello!

The [preinstall.sh](https://github.com/lovell/sharp/blob/master/preinstall.sh) script currently needs `sudo` access to take advantage of the various Linux package managers. I suspect that requirement/check could be skipped when using Darwin+homebrew so I'd be happy to accept a PR to correct this behaviour, especially as you're in a position to test it first :)

(There's plenty of discussion about removing the need for the OS-level dependency of libvips over at https://github.com/lovell/sharp/issues/42)
