### ISSUE TITLE
Request: Support a way to change MaxSize by myself.

### ISSUE THREAD

**Issue by igsr5** [h2non/bimg#404]
### I would like a way to change MaxSize by myself.

https://github.com/h2non/bimg/blob/v1.1.7/options.go#L13
```go
// MaxSize defines the maximum pixels width or height supported.
MaxSize = 16383
```

Currentry, constant `MaxSize` is defined in options.go as width, height validation values. Specifically, it is used for the followring.

https://github.com/h2non/bimg/blob/v1.1.7/vips.go#L567
```go
if width > MaxSize || height > MaxSize {
	return nil, errors.New("Maximum image size exceeded")
}
```

Currently, MaxSize is fixed at 16383 and cannot be changed by you. However our usage require to work with larger images, such as 20,000px.

Therefore, I would like to support way to change MaxSize by myself.

e.g.  
```go
var MaxSize = 16383

// or

var maxSize = 16383

func MaxSize() int {
  return maxSize
}

func SetMaxsize(s int) error {
  if s <= 0 {
    return fmt.Errorf("invalid size.A size must be 0.")
  }

  maxSize = s

  return nil
}

**Comment by h2non** [comment]
Feature supported already. Closing.
