### ISSUE TITLE
Greyscale support

### ISSUE THREAD

**Issue by ismasan** [h2non/bimg#45]
Is there an API to convert images to greyscale currently? Looking at the code I can see that [this line](https://github.com/h2non/bimg/blob/5d322714eca2bd01facdb201651578e77ba8fd11/vips.go#L236) would allow me to pass the necessary options down to Vips, but I'm not sure how to go about it.

Regards.

**Comment by h2non** [comment]
You're right. Unfortunately the API [doesn't support](https://github.com/h2non/bimg/blob/master/vips.h#L140) passing a custom color space.
I can support, or if you can't wait feel free to send a PR.

Supported color spaces in `libvips`:
http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsImage.html#VipsInterpretation

**Comment by h2non** [comment]
This is in master now. I'll close another issue before releasing a new version, hopefully tomorrow.

Please, note that the interpretation constants has been renamed:
https://github.com/h2non/bimg/blob/master/options.go#L63

**Comment by h2non** [comment]
I made some refactors. For further details, see: https://github.com/h2non/bimg/commit/ed4faadba6169ce92d4ffaa8ed9e7a8a41a85917

**Comment by ismasan** [comment]
Hey @h2non , this is fantastic! Thanks so much for the great work.

**Comment by h2non** [comment]
@ismasan Give thanks to @greut which made the initial implementation for this feature.

**Comment by h2non** [comment]
@ismasan FYI a fresh `0.1.18` version was released with [this feature](https://github.com/h2non/bimg#custom-colour-space-black--white). Feel free to update `bimg`!
