### ISSUE TITLE
does bimg have any mem leaks?

### ISSUE THREAD

**Issue by winens** [h2non/bimg#454]
im processing images to convert them into smaller webp images.
this is what it look like when i didnt process any images:
![image](https://github.com/h2non/bimg/assets/52735546/27c0c97d-fdea-4895-94ad-86938da2c6c7)

and this is when  i process images:
![image](https://github.com/h2non/bimg/assets/52735546/53618166-4b8d-40a1-b297-0ec177993983)

may be it doesnt free the memory? i don't know, but when i process another new image, the memory is still increasing.
![image](https://github.com/h2non/bimg/assets/52735546/af58071b-909b-484d-b774-f85cd6df37e8)

is this normal?

**Comment by Winens** [comment]
the memory has been free after a while. everything is okey.
