### ISSUE TITLE
ICC profile support.

### ISSUE THREAD

**Issue by bfitzsimmons** [h2non/bimg#50]
Any plans for supporting the modification of color profiles?

**Comment by h2non** [comment]
I would not mind to include support to work with specific ICC profiles, but honestly this is not in my short term plans.

If you need this feature asap, feel free to go ahead first, and I'll be glad to help you during the journey. The implementation should be consistent and doesn't break the existing API contract.

A few resources I've just saw to get started:
http://www.vips.ecs.soton.ac.uk/supported/7.40/doc/html/libvips/libvips-colour.html#vips-icc-transform
http://libvips.blogspot.co.uk/2012/11/new-colour-package.html

The following code could be a start point. Try calling it from Go via FFI:
```c
int
vips_transform_bridge (VipsImage *in, VipsImage **out, const char *icc) {
  // `icc` represents the absolute path to the ICC file
  return vips_icc_transform(in, &out, icc, "embedded", TRUE, NULL)) {
}
```

**Comment by h2non** [comment]
@bfitzsimmons Just to move forward with the feature, have you been working in supporting it?

**Comment by bfitzsimmons** [comment]
Sorry for the silence.

I haven't yet moved forward on this. I would still love to see the functionality, but I don't currently have time to work on it.
