### ISSUE TITLE
Slow webp convert

### ISSUE THREAD

**Issue by d-g-laptev** [h2non/bimg#54]
Hello, 

I have very slow convert to webp (all other results are +- the same, but Convert to webp is 1000 times slower) - it was checked on your benchmarks

Please, help to find problem...

**Comment by h2non** [comment]
`webp` benchmarks are not correct in the past. Take a look now.

Roughly it should take between 10 and 30 ms to convert a medium size `webp` image.

**Comment by h2non** [comment]
Benchmarks are now fixed. There's no known issue in terms of performance.
