### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ismasan** [h2non/bimg#56]
Hi. The following is a simplified version of an HTTP server that resizes and serves an image off the filesystem.

Opening the same image in the browser several times (on `localhost:8080`), I can see the process memory going up. The more times I hit the server, the more the memory goes up, and stays there. It doesn't seem to go back down.

```golang
package main

import (
	"fmt"
	"html"
	"io/ioutil"
	"log"
	"net/http"

	bimg "gopkg.in/h2non/bimg.v0"
)

func main() {
	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		bytes, err := ioutil.ReadFile("./fixtures/29/original/111900-_MG_2031.JPG")
		if err != nil {
			fmt.Fprintf(rw, "Err, %q", html.EscapeString(r.URL.Path))
			return
		}

		bimgImg := bimg.NewImage(bytes)

		var opts bimg.Options
		opts.Interpolator = bimg.BILINEAR
		opts.Width = 200
		opts.Height = 300
		opts.Enlarge = true

		newImage, err := bimgImg.Process(opts)
		if err != nil {
			fmt.Fprintf(rw, "Bimg Err, %q", html.EscapeString(r.URL.Path))
			return
		}
		rw.Write(newImage)
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

This is happening in my MacBook Pro and also an Ubuntu machine. I tried with Go 1.4.2 and 1.5.1. Similar results.

<img width="700" alt="screenshot 2015-09-29 21 16 51" src="https://cloud.githubusercontent.com/assets/1081/10177036/e640c2c4-66ef-11e5-804d-072aa7e9a68f.png">
<img width="705" alt="screenshot 2015-09-29 21 17 11" src="https://cloud.githubusercontent.com/assets/1081/10177041/ec435010-66ef-11e5-9271-a1da3c3cdb12.png">
<img width="717" alt="screenshot 2015-09-29 21 16 26" src="https://cloud.githubusercontent.com/assets/1081/10177045/f12648e4-66ef-11e5-8f3e-1596b5e84dd7.png">

This last one is after hammering the server with `ab -n 1000 -c 3 http://127.0.0.1:8080/`. It stays there and doesn't go back down.

<img width="702" alt="screenshot 2015-09-29 21 53 42" src="https://cloud.githubusercontent.com/assets/1081/10178103/a43f22b6-66f5-11e5-9a39-a0c3f37341e7.png">

For good measure, I tried the following script that just reads the file and serves the bytes, without Bimg. That version tops at ~6.7MB and stops there, so no apparent leak.

```golang
package main

import (
	"fmt"
	"html"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		bytes, err := ioutil.ReadFile("./fixtures/29/original/111900-_MG_2031.JPG")
		if err != nil {
			fmt.Fprintf(rw, "Err, %q", html.EscapeString(r.URL.Path))
			return
		}

		rw.Write(bytes)
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}

// top: 6.7MB. No leak.
```

Have you encountered this? Or maybe I'm missing something obvious in the way I'm using Bimg?

Regards.

**Comment by ismasan** [comment]
A bit more, for reference: I run the following test using the [Vips Go package](https://github.com/DAddYE/vips), and memory seams to peak at ~67MB, no apparent leak.

```golang
package main

import (
	"fmt"
	"html"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/daddye/vips"
)

func main() {
	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		bytes, err := ioutil.ReadFile("./fixtures/29/original/111900-_MG_2031.JPG")
		if err != nil {
			fmt.Fprintf(rw, "Err, %q", html.EscapeString(r.URL.Path))
			return
		}

		opts := vips.Options{
			Width:        200,
			Height:       300,
			Crop:         false,
			Extend:       vips.EXTEND_WHITE,
			Interpolator: vips.BILINEAR,
			Gravity:      vips.CENTRE,
			Quality:      95,
		}

		newImage, err := vips.Resize(bytes, opts)
		if err != nil {
			fmt.Fprintf(rw, "Bimg Err, %q", html.EscapeString(r.URL.Path))
			return
		}
		rw.Write(newImage)
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}

```

**Comment by h2non** [comment]
You're totally right. At some point in the last 2 months one memory leak was introduced. It's a bit silly actually, and unfortunately it has impact on every image processed by `bimg`.

I was surprised since I'm running `bimg` via [`imaginary`](https://github.com/h2non/imaginary) without any memory troubles in production processing a bunch of images per day, but I'm using an relatively old version of `bimg`.

I've passed the `bimg` and [`imaginary`](https://github.com/h2non/imaginary/blob/master/bench.sh) benchmarks and the RSS memory is stable now. In some scenarios, especially in network IO with high concurrency, Go runtime usually takes more than 100MB for the virtual memory in order to guarantee a proper performance (mostly due to goroutines and GC), so don't be afraid if it grows up to 200MB, then it should release memory when you stop stressing the server.

I'm gonna release a fresh version with this fix.
Thanks for reporting!

**Comment by ismasan** [comment]
I can confirm that this is fixed. Thank you so much for the great work!

**Comment by h2non** [comment]
Excellent, so I'm gonna close this for now.
