### ISSUE TITLE
Bimg Crashes with some images

### ISSUE THREAD

**Issue by jutaz** [h2non/bimg#58]
Hello,
Got this crash the other day:
```
	/usr/lib/golang/src/runtime/sigpanic_unix.go:14 +0x5e
goroutine 1916 [syscall, locked to thread]:
runtime.cgocall_errno(0x4044d0, 0xc20806e350, 0x0)
	/usr/lib/golang/src/runtime/cgocall.go:130 +0xf5 fp=0xc20806e330 sp=0xc20806e308
github.com/h2non/bimg._Cfunc_vips_affine_interpolator(0x7fda73478e30, 0xc20806e398, 0x3fe3faa84acbe8d9, 0x0, 0x0, 0x3fe3faa84acbe8d9, 0x7fda0400b720, 0x0)
	/root/src/github.com/h2non/bimg/:99 +0x43 fp=0xc20806e350 sp=0xc20806e330
github.com/h2non/bimg.vipsAffine(0x7fda73478e30, 0x3fe3faa84acbe8d9, 0x3fe3faa84acbe8d9, 0x0, 0x0, 0x0, 0x0)
	/root/src/github.com/h2non/bimg/vips.go:381 +0x198 fp=0xc20806e3d0 sp=0xc20806e350
github.com/h2non/bimg.transformImage(0x7fda73478e30, 0x167, 0x280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x50, 0x6, ...)
	/root/src/github.com/h2non/bimg/resize.go:171 +0x4ae fp=0xc20806e558 sp=0xc20806e3d0
github.com/h2non/bimg.Resize(0xc208130000, 0x84ef, 0xfe00, 0x167, 0x280, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/src/github.com/h2non/bimg/resize.go:85 +0x942 fp=0xc20806ea18 sp=0xc20806e558
github.com/h2non/bimg.(*Image).Process(0xc2082ec6a0, 0x0, 0x280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/src/github.com/h2non/bimg/image.go:155 +0xa0 fp=0xc20806eb68 sp=0xc20806ea18
github.com/h2non/bimg.(*Image).Enlarge(0xc2082ec6a0, 0x280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/src/github.com/h2non/bimg/image.go:56 +0xc4 fp=0xc20806ed60 sp=0xc20806eb68
```

Unfortunately I have no image that caused the crash since that happened in production.

The library was checked out at https://github.com/h2non/bimg/releases/tag/0.1.20

Happy to help, if there is anything I can do.

**Comment by h2non** [comment]
Thanks for reporting.

A couple of tips that might help:
- Be sure you're running the latest version of `bimg` and try it again.
- You can use `GOTRACEBACK=1` env variable for debugging
- You can implement a [recover mechanism](https://github.com/golang/go/wiki/PanicAndRecover) to handle panics and avoid process exit. 

Some extra more of information would help me to reproduce the issue.
- Are you calling bimg from an network service (e.g: HTTP server)
- Are you calling `bimg` from a potentially high concurrent environment?
- Which version of Go and libvips are you using?
- Can you share the options you're passing to `bimg`

**Comment by jutaz** [comment]
> Be sure you're running the latest version of bimg and try it again.

Latest version seems not to have crashes so far. But it may be coincidence.

> You can implement a recover mechanism to handle panics and avoid process exit.

Planning on doing that.

> Are you calling bimg from an network service (e.g: HTTP server)

Yes, `bimg` is used as image processor in REST service.

> Are you calling bimg from a potentially high concurrent environment?

I would not say it is high concurrency. few uploads a minute, with some peaks. But in my tests it was perfectly fine with `6` req/s, so it should not be it.

> Which version of Go and libvips are you using?

`go` `1.4.2`.

`libvips` - `8.0.2`

> Can you share the options you're passing to `bimg`

Nothing fancy. Just `Quality` of `50` and few sizes (`250`, `640`, etc.)

**Comment by h2non** [comment]
Thanks for the info. I'll try to reproduce a similar environment, but a testing image would be great.

Please note that libvips `8.0.x` was not fully tested and minor issues may happen. 
If you are open to, use `7.42.x` instead.

Ideally, the panic handler should not exists in your code, but until it's verified that this could be an issue of `libvips`, and would prefer do not add any panic handler in `bimg`. Use it as a temporal workaround until the issue is resolved.

If you're running an HTTP service exclusively to process images, you can consider using [imaginary](https://github.com/h2non/imaginary), which is essentially an HTTP layer to `bimg`. Using it from Docker is pretty trivial.

`bimg`, and `imaginary` as well, has benchmarks suites, even with high concurrency, and that should not be the origin of the issue, but just mention in the past I reported an issue to `libvips` due to a concurrency issue while reading buffers, but it was mitigated in current `libvips` versions.

**Comment by jutaz** [comment]
Yes, I saw `imaginary` and I very liked it, but we have a bit different model (we pre-process images) for storing images, so I had to create a similar thing to `imaginary`.

So far there are no issues with latest version of `bimg`. Will keep you posted, though.

Thanks for looking into this.

**Comment by h2non** [comment]
Just to clarify... I can confirm that `bimg`, as far as I've tested, works properly with `libvips` 8.x.

btw... something new about this?

**Comment by h2non** [comment]
I'll close this for now due to inactivity. If you experimented some issue related to this, let it know and we can reopen the issue.

**Comment by jutaz** [comment]
Nope, looks like this is all good, thanks! So far running 24/7 I have not seen this issue appear in logs :+1:
