### ISSUE TITLE
Background Color (Option) not working when resizing jpeg images

### ISSUE THREAD

**Issue by ribeirofelix** [h2non/bimg#59]
I'm trying to resize and embed images in a white background

here is my options:

```
	options := bimg.Options{
			Width:      widht,
			AreaWidth:  widht,
			AreaHeight: height,
			Height:     height,
			Crop:       false,
			Embed:      true,
			Quality:    95,
			Background: bimg.Color{255,255,255},
		}
```

But the resized images still in black background.

Is it a bug? Is this supported? 

Thanks!!

**Comment by h2non** [comment]
Background feature is only valid for PNG images.

**Comment by h2non** [comment]
It works exclusively with PNG images. Unless you claim that the issue happen with PNG images (not JPEG), I'm gonna close this for now.

**Comment by ribeirofelix** [comment]
No. It really just happens with non-PNG images.
Thanks :)

**Comment by alehano** [comment]
But how can I resize and embed jpeg with white background?
