### ISSUE TITLE
image.Extract() with 0 top and left

### ISSUE THREAD

**Issue by ismasan** [h2non/bimg#60]
This works as expected:

```golang
newImage, err = bimgImg.Extract(10, 20, 200, 300)
```

It extracts an are of dimensions 200x300, starting at point 10x20 of the original image,

When _top_ and _left_ are 0, however, it doesn't seem to do anything. It just returns the original dimensions.

```golang
newImage, err = bimgImg.Extract(0, 0, 200, 300)
```

I guess one solution would be to use `#Crop` when top and left are 0, but maybe it would make sense for `#Extract` to also work when extracting from the top left corner of the original.

Looking at the code I can see that extraction only kicks in when top and left are greater than 0.

https://github.com/h2non/bimg/blob/master/resize.go#L232

Regards

**Comment by h2non** [comment]
I see. In that case it should be forced in some way passing some additional option. I'll take a look.

**Comment by h2non** [comment]
Fixed. Now you can pass `0` top and left params to `image.Extract()`. `bimg` will handle it correctly.
