### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by robzienert** [h2non/bimg#61]
I have a project that needs to support SVG operations and this library looks like a good foundation to build on. Do you have any insight on the level of effort to add support - I will gladly open a PR for this functionality.

**Comment by h2non** [comment]
Technically speaking, `libvips` can process SVG (and other formats) relying on `libmagick` bindings. 
I have no plans to support it now, but if you need the feature, go ahead. I'm totally open to accept PRs if the implementation is reliable.

A couple of months ago I [introduced initial](https://github.com/h2non/bimg/blob/master/type.go#L11) support for `libmagick` formats, so if [you compile](https://github.com/jcupitt/libvips#imagemagick-or-optionally-graphicsmagick) `libvips` with `libmagick`, so can test it, but I didn't tried yet.

**Comment by h2non** [comment]
This feature out of scope and there are no plans to support it in a medium term period. Closing.
