### ISSUE TITLE
adding sharpen function?

### ISSUE THREAD

**Issue by cneerdaels** [h2non/bimg#64]
Llibvips has a vips_sharpen function. I don't know go well enough to expose this in bimg - or I'd suggest a patch. Is this a difficult addition?

**Comment by h2non** [comment]
Supporting it is not difficult. I'm open for PRs if the implementation is consistent and follow the existent patterns.

See this PR as similar implementation reference: https://github.com/h2non/bimg/pull/52

**Comment by h2non** [comment]
Feature supported. I believe we can close this.
