### ISSUE TITLE
Extract argument order inconsistent?

### ISSUE THREAD

**Issue by cneerdaels** [h2non/bimg#65]
I was having a hard time figuring out why my extraction wasn't working, and realized I had assumed the argument order was the same as vips_extract_area(left, top, width, height) but realized in bimg the first two are swapped:

func (i *Image) Extract(top, left, width, height int) ([]byte, error) 

While the order is certainly subjective, I just wanted to ask  whether it was intentional?

thanks

**Comment by h2non** [comment]
I wasn't intentional. Ideally it should have the same interface as `libvips`, but we can't change it now since it will break the interface contract.

**Comment by h2non** [comment]
Nothing more to add here. Closing for now.
