### ISSUE TITLE
Tests Fail - VipsOperation: class \"webpload_buffer\" not found

### ISSUE THREAD

**Issue by chonthu** [h2non/bimg#68]
~/g/s/g/h/bimg.v0 git:master ❯❯❯ go test
--- FAIL: TestImageWatermark (0.08s)
	image_test.go:164: VipsOperation: class "text" not found

	image_test.go:169: Unsupported image format
	image_test.go:173: Image is not jpeg
--- FAIL: TestImageWatermarkNoReplicate (0.08s)
	image_test.go:195: VipsOperation: class "text" not found

	image_test.go:200: Unsupported image format
	image_test.go:204: Image is not jpeg
--- FAIL: TestSize (0.00s)
	metadata_test.go:23: Cannot read the image: &errors.errorString{s:"VipsOperation: class \"webpload_buffer\" not found\n"}
--- FAIL: TestMetadata (0.00s)
	metadata_test.go:49: Cannot read the image: test.webp -> VipsOperation: class "webpload_buffer" not found
--- FAIL: TestImageInterpretation (0.00s)
	metadata_test.go:83: Cannot read the image: test.webp -> VipsOperation: class "webpload_buffer" not found
--- FAIL: TestColourspaceIsSupported (0.00s)
	metadata_test.go:103: Cannot read the image: test.webp -> VipsOperation: class "webpload_buffer" not found
--- FAIL: TestConvert (0.04s)
	resize_test.go:215: Resize(imgData, bimg.Options{Height:240, Width:300, AreaHeight:0, AreaWidth:0, Top:0, Left:0, Extend:0, Quality:0, Compression:0, Zoom:0, Crop:true, Enlarge:false, Embed:false, Flip:false, Flop:false, Force:false, NoAutoRotate:false, NoProfile:false, Interlace:false, Rotate:0, Background:bimg.Color{R:0x0, G:0x0, B:0x0}, Gravity:0, Watermark:bimg.Watermark{Width:0, DPI:0, Margin:0, Opacity:0, NoReplicate:false, Text:"", Font:"", Background:bimg.Color{R:0x0, G:0x0, B:0x0}}, Type:2, Interpolator:0, Interpretation:0, GaussianBlur:bimg.GaussianBlur{Sigma:0, MinAmpl:0}, Sharpen:bimg.Sharpen{Radius:0, X1:0, Y2:0, Y3:0, M1:0, M2:0}}) error: &errors.errorString{s:"VipsOperation: class \"webpsave_buffer\" not found\n"}
	resize_test.go:219: Image is not png
--- FAIL: TestVipsRead (0.00s)
	vips_test.go:23: Empty image
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x60 pc=0x43d86ac]

runtime stack:
runtime.throw(0x41eec80, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 72 [syscall, locked to thread]:
runtime.cgocall(0x4002b20, 0xc820041d08, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820041cd8 sp=0xc820041ca8
gopkg.in/h2non/bimg%2ev0._Cfunc_vips_colourspace_issupported_bridge(0x0, 0xc800000000)
	??:0 +0x35 fp=0xc820041d08 sp=0xc820041cd8
gopkg.in/h2non/bimg%2ev0.vipsColourspaceIsSupported(0x0, 0xc82002e0d0)
	/Users/meppurathu/go/src/gopkg.in/h2non/bimg.v0/vips.go:243 +0x21 fp=0xc820041d20 sp=0xc820041d08
gopkg.in/h2non/bimg%2ev0.vipsPreSave(0x0, 0xc820041df0, 0x0, 0x0, 0x0)
	/Users/meppurathu/go/src/gopkg.in/h2non/bimg.v0/vips.go:293 +0x88 fp=0xc820041d58 sp=0xc820041d20
gopkg.in/h2non/bimg%2ev0.vipsSave(0x0, 0x5f, 0x0, 0x0, 0x0, 0x16, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/meppurathu/go/src/gopkg.in/h2non/bimg.v0/vips.go:307 +0x97 fp=0xc820041de8 sp=0xc820041d58
gopkg.in/h2non/bimg%2ev0.TestVipsWatermark(0xc82009ad80)
	/Users/meppurathu/go/src/gopkg.in/h2non/bimg.v0/vips_test.go:90 +0x22b fp=0xc820041f68 sp=0xc820041de8
testing.tRunner(0xc82009ad80, 0x428f068)
	/usr/local/go/src/testing/testing.go:456 +0x98 fp=0xc820041fa0 sp=0xc820041f68
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820041fa8 sp=0xc820041fa0
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x4202f20, 0x428ec00, 0x32, 0x32, 0xc82004fe00)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82040fef8, 0xc82004fe00)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	gopkg.in/h2non/bimg.v0/_test/_testmain.go:190 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
FAIL	gopkg.in/h2non/bimg.v0	4.860s

~/g/s/g/h/bimg.v0 git:master ❯❯❯ vips --version
vips-8.0.2-Fri Aug 14 18:18:27 EDT 2015

**Comment by h2non** [comment]
You've to compile `libvips` with `pangoft2` bindings. See: https://github.com/jcupitt/libvips#pangoft2

The bash install script already provides support for it.

**Comment by chonthu** [comment]
Running `brew install homebrew/science/vips --with-imagemagick --with-webp` seemed to have worked! Thanks again for your help. I have a couple of other issue ill make separate requests
