### ISSUE TITLE
Custom Top, Left parameters not being used in crop

### ISSUE THREAD

**Issue by chonthu** [h2non/bimg#69]
https://github.com/h2non/bimg/blob/master/resize.go#L227

As you can see regardless of what the user passes to the top, left parameter, when cropping those numbers are discarded for gravity params

So to give a background on what i'm trying to do. I have an image 800 x 800:
Im trying to get top:20 left:20, areaWidth: 700, areaHeight:700, outWidth: 400x400

Maybe good to write this out as a test? But i don't see anything where we could test position.

**Comment by chonthu** [comment]
I can create a pull request, but a possible fix is the following

   		var left, top int

		left, top = calculateCrop(inWidth, inHeight, o.Width, o.Height, o.Gravity)

		if o.Top != 0 || o.Left != 0 {
			left, top = o.Left, o.Top
		}

**Comment by h2non** [comment]
Feel free to go ahead and cover the new behavior with some test. Then I'll review in detail the PR.

**Comment by chonthu** [comment]
Closing this as I can already do this by doing an extract first, then cropping
