### ISSUE TITLE
cgo error?

### ISSUE THREAD

**Issue by gyf19** [h2non/bimg#71]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x10 pc=0x7f122d808151]

runtime stack:
runtime.gothrow(0x8f9450, 0x2a)
	/usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1412 [syscall, locked to thread]:
runtime.cgocall_errno(0x404780, 0xc20849ec00, 0x0)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20849ebe0 sp=0xc20849ebb8
base/bimg._Cfunc_vips_affine_interpolator(0x7f11e4061010, 0xc20849ec48, 0x3fe95810624dd2f2, 0x0, 0x0, 0x3fe95810624dd2f2, 0x7f1138002e30, 0x0)
	/home/czx/dev/server/base/src/base/bimg/:100 +0x43 fp=0xc20849ec00 sp=0xc20849ebe0
base/bimg.vipsAffine(0x7f11e4061010, 0x3fe95810624dd2f2, 0x3fe95810624dd2f2, 0x0, 0x0, 0x0, 0x0)
	/home/czx/dev/server/base/src/base/bimg/vips.go:413 +0x198 fp=0xc20849ec80 sp=0xc20849ec00
base/bimg.transformImage(0x7f11e4061010, 0xc6, 0xc6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x50, 0x6, ...)
	/home/czx/dev/server/base/src/base/bimg/resize.go:173 +0x25c fp=0xc20849edb8 sp=0xc20849ec80
base/bimg.Resize(0xc209ac6000, 0x20407, 0x20407, 0xc6, 0xc6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/czx/dev/server/base/src/base/bimg/resize.go:85 +0x8a5 fp=0xc20849f348 sp=0xc20849edb8
base/bimg.(*Image).Process(0xc20849f870, 0xc6, 0xc6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/czx/dev/server/base/src/base/bimg/image.go:165 +0xa0 fp=0xc20849f4a0 sp=0xc20849f348
base/bimg.(*Image).Resize(0xc20849f870, 0xc6, 0xc6, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/czx/dev/server/base/src/base/bimg/image.go:19 +0xc4 fp=0xc20849f6a8 sp=0xc20849f4a0

**Comment by h2non** [comment]
Probably this is an error originated in the C side, but Go runtime has no access to C stack. I would need more information to reproduce the issue.

Please, provide more info about your environment:

- Go version
- libvips version
- bimg version
- Platform (linux, osx...)
- Useful info about the environment that caused the error (image type, image size...)

That

**Comment by gyf19** [comment]
go version: go 1.4.3
libvips version: vips-8.0.2
bimg version: 0.1.21
Platform : Red Hat Enterprise Linux Server release 6.5
image type : jpg
image size : unknown

**Comment by h2non** [comment]
Bimg is used from a network service, like an HTTP service?
As work around, you can try rcovering the error in Go to jandle it more properly, and for instance, save details of the error, such as image file.

**Comment by gyf19** [comment]
use recovering the panic
