### ISSUE TITLE
GLib assertion failed error

### ISSUE THREAD

**Issue by jutaz** [h2non/bimg#72]
I started seeing errors after running `bimg` for a while on production:
```
(bimg:26621): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
```

Running `bimg@0.1.21` and `vips@8.0.1`. Bimg is used in HTTP server, not a big concurrency one, though.

Restart seems to fix this, and it takes 1-2 weeks till this starts popping in again.

**Comment by h2non** [comment]
Seems like the pointer is not available anymore when the `unref` is called. I don't believe this is directly related to a long-running process nature issue.

Can you provide some stack trace or similar? I would like to see where it failed in the C code.

If @jcupitt don't mind, he might provide some more direct ideas about the possible origin or nature of this kind of issue.

**Comment by jutaz** [comment]
What is weird, that there is no stack trace, just this message. Also, AFAIK images convert just fine, this is just an annoying message that appears in logs :)

**Comment by jcupitt** [comment]
You can make it dump a core on assert failure, you put this somewhere in your startup:

```
        g_log_set_always_fatal(
                G_LOG_FLAG_RECURSION |
                G_LOG_FLAG_FATAL |
                G_LOG_LEVEL_ERROR |
                G_LOG_LEVEL_CRITICAL |
                G_LOG_LEVEL_WARNING );
```

Or set the `G_DEBUG` environment variable:

```
export G_DEBUG=fatal-warnings,fatal-criticals
```

Now any message will cause an immediate `abort()`, which should make a coredump. It sounds like it could be difficult to reproduce :-(

**Comment by h2non** [comment]
Debug [helpful info](https://github.com/h2non/bimg#debugging) added to the readme. I believe there's nothing more to add here. Closing.
