### ISSUE TITLE
White background when embed.

### ISSUE THREAD

**Issue by alehano** [h2non/bimg#74]
Hi. How can I set white background when I do "Embed"?
Now I have ugly edges:

![image](https://cloud.githubusercontent.com/assets/1269330/11977812/3ca94a66-a997-11e5-9c62-75a1b559363a.png)

**Comment by h2non** [comment]
You can try passing the `Background` field with the proper `Color` struct representing the RGB scheme.

Currently it's only supported for PNG images, but you can try removing that constraint in your fork. The code is just here:
https://github.com/h2non/bimg/blob/master/resize.go#L317
