### ISSUE TITLE
Package libvips in repo.

### ISSUE THREAD

**Issue by gaillard** [h2non/bimg#78]
One of the things that makes the golang sqlite package so easy to use and popular is the c source is right in the repo. Would that be possible here, or is there some kind of code generation going on?

**Comment by h2non** [comment]
There're no plans to embed `libvips` C source in this repository. The [preinstall.sh](https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh) provides all you need to install it in a simple way in a variety of platforms.

**Comment by gaillard** [comment]
Sure would help cross compiles and relying on some shell script from a node repo. Aren't the versions in that file specific to that node module?

**Comment by h2non** [comment]
`bimg` is compatible with `libvips` `^7.40`, `8.0`, `8.1` and `8.2`, but in this last one I didn't tried yet. The bash script a simple, convenient and generic, having no significant coupling to the node.js project. The desired `libvips` version is the unique thing that might change in the future.

**Comment by chreble** [comment]
IMHO, it would be better to use `Docker` for testing against different `libvips` version.
https://github.com/marcbachmann/dockerfile-libvips

**Comment by h2non** [comment]
Yes, totally. It's already used from [imaginary](https://github.com/h2non/imaginary). Thanks @chreble.
