### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by gaillard** [h2non/bimg#80]
any reason this package doesn't just call into the vips resize function itself?

It is hard to tell what the operations do here since they do not map one to one with vips, and the documentation is very sparse. For example, does resize do multi step halving with bilinear and then default to the cubic filter when close to the target size? Are the intermediates cached?

**Comment by h2non** [comment]
`bimg` is not a Go bridge to `libvips` C API. It only uses `libvips` for convenience since it's a powerful and fast library for image processing, therefore the API and versatility of the image processing is so limited by design now. That said only certain common high-level operations are supported. The image is processed in a pipeline of operations and those operations are performed atomically.

**Comment by gaillard** [comment]
If this library is a generic go package that is not supposed to be a wrapper, then all the more reason to put the c dependency (all) code into the repo like mattn/sqlite does. This is kind of a response to #78. Yes there is that script to get vips but locking down versions is one of the big reasons to the new vendoring support.

**Comment by h2non** [comment]
I don't agree about versioning third-party C in this repository. SQLite has a very small codebase compared to `libvips`, but in any case you don't have to do it. Today there're a lot of tools to deal properly with dependency hell and packages versioning efficiently. You can provision the (compatible) version you desire in the way is more convenient for you, regardless of using a bash script, apt/yum, Puppet, Ansible or any other tool.

Finally, it's just open source, you're free to fork it and do what ever you want.

**Comment by h2non** [comment]
BTW I believe there's nothing more to discuss here, so I closed the issue. If not, let me know and I can reopen it.

**Comment by gaillard** [comment]
No problem, I mentioned this in the vips repo so i'll pursue it there :)
