### ISSUE TITLE
No stable release / v1

### ISSUE THREAD

**Issue by jeroenvdheuvel** [h2non/bimg#82]
This package doesn't have a stable release yet. There are some tags 0.1.*, but these tags are not considered stable by gopkg.in.

I would like to have a build tag that I can consider stable (api doesn't change radically between minor versions). Is this package mature enough to be tagged as v1.0.0?

A quote from gopkg.in:
> Packages should not remain in v0 for too long, as the lack of API stability hinders their adoption, and hurts the stability of packages and applications that depend on them.

[gopgk.in version zero explanation](http://labix.org/gopkg.in#VersionZero)

**Comment by h2non** [comment]
Got it, however I would like to perform some breaking changes before moving to `v1`. 
The unique thing I can guarantee you is that no breaking changes will be introduced in `v0` and the package was stable for a long time.

Let's keep this open to track until major version change is done.

**Comment by h2non** [comment]
bimg `v1` is out! Some minor breaking changes has been introduced. You can see all the changes [here](https://github.com/h2non/bimg/commit/c57a8c1320b6c6de185427ce60c47fa5487e66b8).
