### ISSUE TITLE
Watermark x,y start

### ISSUE THREAD

**Issue by aworobel** [h2non/bimg#84]
Hello,

It would be great if we cam choose the x,y start of the watermark.
I used all the available options to be closed as possible at the top left corner but it is not possible.

Could it be improved ?

Thanks a lot.
Arnaud.

**Comment by h2non** [comment]
Not supported yet. You've to play with Width, Margin and NoReplicate options.

**Comment by aworobel** [comment]
Thanks for your fast answer.
Yes i use them, but very difficult on little thumbmails : )

**Comment by h2non** [comment]
I would not mind accepting this feature as PR. Feel free to go ahead with it.

**Comment by aworobel** [comment]
Thanks, i will have a look or not watermark the thumbmails  :)
