### ISSUE TITLE
Resizing a PNG does not work when setting a white background, but works when setting a black one.

### ISSUE THREAD

**Issue by henry-blip** [h2non/bimg#87]
I'm resizing a PNG file with these options:

`bimg.Options{
  Type:  bimg.JPEG,
  Background: bimg.Color{255, 255, 255}
}`

It gives this error, which I think comes from libvips:
`linear: vector must have 1 or 2 elements`

However, if I switch to using a black background, the resize occurs with no error:
`bimg.Options{
  Type:  bimg.JPEG,
  Background: bimg.Color{0, 0, 0}
}`

It seems like the error occurs in vipsFlattenBackground, and is avoided if the background is black:
```
func imageFlatten(image *C.VipsImage, imageType ImageType, o Options) (*C.VipsImage, error) {
	// Only PNG images are supported for now
	if imageType != PNG || o.Background == ColorBlack {
		return image, nil
	}

	return vipsFlattenBackground(image, o.Background)
}
```

This seems to happen on images that contain only 1 or 2 colors.

**Comment by henry-blip** [comment]
Found the issue, I've opened a pull request: https://github.com/h2non/bimg/pull/88

**Comment by h2non** [comment]
Merged. Thank you.
