### ISSUE TITLE
Linking Error when using distro package libvips

### ISSUE THREAD

**Issue by daemonfire300** [h2non/bimg#89]
Hi there,

on 16.04 it is not sufficient to install libvips from the packages which throws the following error: `/usr/bin/ld: warning: libIlmImf.so.6, needed by /usr/local/lib/libvips.so`

If I use your provided install script it works.

```
/usr/lib/x86_64-linux-gnu/libvips.so
/usr/lib/x86_64-linux-gnu/libvips.so.38
/usr/lib/x86_64-linux-gnu/libvips.so.38.0.4
/usr/local/lib/libvips.so
/usr/local/lib/libvips.so.42
/usr/local/lib/libvips.so.42.3.0

xxx@xxxx  ~  locate libIlmImf
/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22
/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
/usr/lib/x86_64-linux-gnu/libIlmImf.a
/usr/lib/x86_64-linux-gnu/libIlmImf.so
/usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22
/usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22.0.0
/usr/lib/x86_64-linux-gnu/libIlmImfUtil.a
/usr/lib/x86_64-linux-gnu/libIlmImfUtil.so

```

This is with libvips installed via packages + the installer.

It would be nice if this works with the default packages provided by the distros. If anyone can point me to an entrypoint for a solution I will try to work on resolving this issue by myself, but as of right now I do not know what to do to make this compatible with the distro packages.

kind regards

**Comment by h2non** [comment]
Deprecated. Closing.
