### ISSUE TITLE
support vips_resize

### ISSUE THREAD

**Issue by ingardm** [h2non/bimg#94]
vips_resize used by vipsthumbnail seemingly produce smaller size files

**Comment by aarti** [comment]
@h2non I have this working on my branch with the new vips_resize() which supports lanczos3 for downsampling, do you want this upgrade, I can PR?

**Comment by h2non** [comment]
That would be nice, thank you!

**Comment by xenji** [comment]
Hey, any news on this one? This improvement would be highly appreciated over here :D.
@aarti I looked at your fork, but I did not find the commit(s) you are referring to. Can I help with anything?

**Comment by aarti** [comment]
I am unable to submit this at the moment, there are some restrictions around the work I did.

**Comment by laszbalo** [comment]
What would be the effect of supporting vips_resize for image quality? ATM, I get substantially worse image quality when using bimg compared to what I get with calling vips resize (lanczos3 as default) from the command line.

**Comment by xenji** [comment]
@laszbalo I would guess that is because of the use of bilinear, bicubic or nohalo as only available options for the current resize.

**Comment by laszbalo** [comment]
@xenji Thanks, that makes sense.

**Comment by xenji** [comment]
I have never done any Go <-> C interaction, but I will give it a shot if you want. Can anybody give me a bit of advice in terms of the implementation strategy? Shall I replace the existing resize function or does it make more sense to build it side by side?

**Comment by aarti** [comment]
Don't recommend replacing existing function .lanczos/vips_resize works best when downsampling.

Vips_affine - the current function is best for upsampling AFAIK

Read up on vips and how these functions are different, they are very good with answering questions.

Good luck with Cgo.
