### ISSUE TITLE
Missing pixel when resizing due to math.Floor

### ISSUE THREAD

**Issue by rogersole** [h2non/bimg#99]
When trying to resize an image of 1920x1080 to a fixed width to 300 (with no height specification), the resulting image has a width of 299 pixels.

Digging into the vips source code, I found that changing the `math.Floor` to `math.Ceil` prevents this rounding down that's always performed, causing the "missing pixel" issue:

In `resize.go`:

```
func imageCalculations(o *Options, inWidth, inHeight int) float64 {
    factor := 1.0
    xfactor := float64(inWidth) / float64(o.Width)
    yfactor := float64(inHeight) / float64(o.Height)

    switch {
    // Fixed width and height
    case o.Width > 0 && o.Height > 0:
        if o.Crop {
            factor = math.Min(xfactor, yfactor)
        } else {
            factor = math.Max(xfactor, yfactor)
        }
    // Fixed width, auto height
    case o.Width > 0:
        factor = xfactor
        o.Height = int(math.Ceil(float64(inHeight) / factor))
    // Fixed height, auto width
    case o.Height > 0:
        factor = yfactor
        o.Width = int(math.Ceil(float64(inWidth) / factor))
    // Identity transform
    default:
        o.Width = inWidth
        o.Height = inHeight
        break
    }

    return factor
}
```

Is it a `math.Floor` for any specific purpose?

**Comment by mikepulaski** [comment]
This part of the code looks like it was ported from [sharp](https://github.com/lovell/sharp).

There was a similar issue filed https://github.com/lovell/sharp/issues/238 which was fixed by commit https://github.com/lovell/sharp/commit/b8885c1faa325aaf711e5ea3335f56462413781c.

I’ll submit a PR.
